development:
  STRIPE_PUBLISHABLE_KEY: 'pk_test_bdy9udztxZGdCPUYeMX6nrz1004OGkZgjU'
  STRIPE_SECRET_KEY:  'sk_test_aYaoJEgGoHQ7zg3BqwHytxhF008qpb5fTN'
  forecast_io_key: 'b57e25a829b2aa78d167dc40ebcf3dbd'
  